### ISSUE TITLE
Stuck trying to install ...

### ISSUE THREAD

**Issue by aiamuzz** [Chocobo1/qBittorrent-flatpak#2]
Hello,

I am trying to follow the instructions you've provided [here](https://github.com/Chocobo1/qBittorrent-flatpak/blob/master/maintainer.md), but i seem to have hit a dead-end here ...

```
flatpak --installation=myFlatpaks install qbt org.qBittorrent.qbittorrent --user
error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
```

help appreciated ...

**Comment by Chocobo1** [comment]
probably you missed `--no-gpg-verify`...
that page is just for myself, so no support ;)
